### ISSUE TITLE
需要 升级 james.xue/ali-safe-api

### ISSUE THREAD

**Issue by gyp719** [xiaoxuan6/laravel-ali-green#48]
Problem 1
    - james.xue/ali-safe-api[2.1.0, ..., 2.1.1] require illuminate/support ~5.0|~6.0|~7.0|~8.0|~9.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - james.xue/laravel-ali-green v3.1.2 requires james.xue/ali-safe-api ^2.1 -> satisfiable by james.xue/ali-safe-api[2.1.0, 2.1.1].
    - Root composer.json requires james.xue/laravel-ali-green v3.1.2 -> satisfiable by james.xue/laravel-ali-green[v3.1.2].

**Comment by xiaoxuan6** [comment]
laravel 版本多少

**Comment by gyp719** [comment]
> laravel 版本多少

Laravel Framework 10.48.4

**Comment by xiaoxuan6** [comment]
> > laravel 版本多少
> 
> Laravel Framework 10.48.4

已升级

重新执行 `require `即可

```shell
composer require "james.xue/laravel-ali-green"
```
